---
title: "Resume"
output: 
  html_document:
    toc: true
    toc_float: true
---

#### This page contains my resume. 

Claire M. Mobley
(941) 893-7990 | cm4070@cumc.columbia.edu | New York, NY

EDUCATION

Columbia University – Mailman School of Public Health New York, NY
Master of Public Health Candidate; Epidemiology; Comparative Effectiveness and Outcomes Research; GPA: 4.06 Expected May 2022
• Relevant Coursework: Health Economics, U.S. and Comparative Health Care Systems & Health Policy, Decision Analysis, SAS, R, Stata, Biostatistics, Categorical Data, Epidemiology I, II, III.

University of Florida – College of Agricultural and Life Sciences & College of Liberal Arts and Sciences Gainesville, FL
Bachelor of Science in Nutritional Sciences & Bachelor of Science in Psychology; GPA: 3.62 May 2020
• Honors College of University of Florida, Dean’s List of College of Liberal Arts and Sciences
• Relevant Coursework: Statistics I & II, Chemistry I & II, Biology I & II, Biochemistry, Genetics, Physiology, Nutrition.

EXPERIENCE

Columbia Mailman School of Public Health Case Competition Course New York, NY
Participant; Student September 2021- Present
• Compete with a team of 3 in multiple complex healthcare delivery and management cases over the course of the year.
• Develop tools to break down healthcare cases, build a foundation of analytical techniques to understand organizational context, and enhance presentation skills to collaboratively formulate viable strategies for clients.

Columbia Mailman School of Public Health Department of Epidemiology New York, NY
Research Assistant; Data Coordinator March 2021- Present
• Perform numerous detailed literature reviews on modifiable risk factors and cancer incidence, analyze relationship between cancer and diet across pooled studies in SAS, and proofread NIH grant proposals to gain insights on risk factors for fatal cancers.
• Master database infrastructure maintenance activities by effectively navigating REDCap, Excel, EPIC, Velos, and Scissor databases for an ongoing pancreatic cancer research study.

Columbia Mailman School of Public Health Columbia Summer Research Institute New York, NY Teaching Assistant July 2021- August 2021
• Assisted in teaching economic evaluation in healthcare with a focus on cost-effectiveness analyses to 30 medical fellows, residents, and faculty interested in conducting preliminary research.
• Managed weekly office hours to answer decision analysis questions and enhanced modeling skills in preparation for in-class workshops.
• Guided scholars through interactive, weekly Excel and TreeAge Pro workshops by creating decision analytic models to answer health policy and patient care questions under uncertainty.

University of Florida Center for Nutritional Sciences Gainesville, FL
Laboratory Research Assistant May 2018- November 2019
• Accurately followed complex research protocols i.e. genotyping through PCR and gel electrophoresis techniques and conducted precise data collection in Excel.
• Collaborated in a team of 6 to study the role of ZIP14 zinc/manganese transporter on overall health outcomes in mutant animal models.
Atlantis Fellowship Zagreb, Croatia
Fellow June 2019
• Selected for 4-week fellowship shadowing physicians in various specialties including Oncology, Psychiatry, and Gastroenterology.
• Examined the dynamics of Croatia’s universal healthcare system through interactions with physicians, other hospital personnel, and patients.

LEADERSHIP AND COMMUNITY SERVICE

Dance Marathon at University of Florida Gainesville, FL
Outreach Team Assistant Director; Captain; Fundraiser August 2016- May 2020
• Passionate leader rising from Fundraiser to Captain to Assistant Director in the most successful student-run philanthropy in the southeast U.S. - individually raised ~ $12,000 in 4 years for the children at UF Health Shands Children’s Hospital; collectively raised ~ $2M annually.
• Elected to plan a 200-attendee gala event entailing creating budget sheets, recruiting potential sponsors, and contacting attendees invested in improving children’s health.
• Facilitated weekly 20-person team brainstorm sessions on engagement event planning, delegated tasks to meet event goals, and devised novel solutions to alter events to a virtual format due to the COVID-19 pandemic.

Global Medical Training Gainesville, FL & Managua, Nicaragua Medical Director; Volunteer December 2017- May 2020
• Leader in an International Humanitarian Organization providing free health services to medically depleted Central American communities.
• Creatively designed and led workshops intended to teach club members basic Spanish terminology, cultural competency skills, and relevant public health knowledge prior to attending their respective service trips.
• Traveled to resource-limited villages to provide medical support for sick patients by employing Spanish speaking competence, critical thinking, and team collaboration to narrow illness causes and formulate multifaceted treatment regimens prior to physician evaluation.

SKILLS AND INTERESTS
• Skills: Qualitative/ Quantitative Methods; SAS; Stata; R; TreeAge Pro; Decision Trees; Markov Models; Cost-Effectiveness Analysis.
• Interests: Crosswords; Recreational Soccer; Hiking; Healthcare Innovation; Pharmaceutical/ Biotechnology news; Science genre novels


